highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: sb2nov/sb2nov.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
title: Juliette Audema
description: Portfolio de Juliette Audema contenant écrits, talks et projets.
url: https://ajuliettedev.com
author: Juliette Audema
twitter:
  username: ajuliettedev
logo: images/contents/NN.png
social:
  name: Juliette Audema
  links:
    - https://x.com/ajuliettedev
    - https://www.linkedin.com/in/juliette-audema/
    - https://github.com/ajuliette
