title:            Sourabh Bajaj
description:      Portfolio website for Sourabh Bajaj
url:              http://sourabhbajaj.com
signoff:          Sourabh Bajaj
google_analytics: 'UA-40495390-2'

author:
  linkedin: sbajaj9
  twitter : sb2nov
  github : sb2nov
  email: sourabh@sourabhbajaj.com

links:
  - name:         About
    url:          /
  - name:         Blog
    url:          /blog
  - name:         GitHub
    url:          http://github.com/sb2nov
    external:     true

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions

highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
    - tables
