highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: sb2nov/sb2nov.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
google_analytics: 'UA-40495390-2'
