title:            Sourabh Bajaj
description:      Sourabh's blog about Computer Science.
url:              http://sourabhbajaj.com
google_analytics: 'UA-40495390-2'

author:
  name: Sourabh Bajaj
  linkedin: sbajaj9
  twitter : sb2nov
  github : sb2nov
  speaker: sb2nov
  email: sourabh@sourabhbajaj.com

# Things to ignore in the build
exclude: [
  'README.md',
  'Gemfile.lock',
  'Gemfile',
  'Rakefile',
  'vendor/',
  'LICENSE',
  'run_with_docker.sh',
  'CNAME']

links:
  - name:         About
    url:          /
  - name:         Blog
    url:          /blog
  - name:         GitHub
    url:          http://github.com/sb2nov
    external:     true

gems:
  - kramdown
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - rouge

highlighter:      rouge
permalink:        pretty
markdown:         kramdown
